-- Insert default courses
INSERT INTO courses (id, title, description, icon) VALUES
('html', 'HTML', 'Learn the foundation of web development with HTML. Master semantic markup, forms, and modern HTML5 features.', '🏗️'),
('css', 'CSS', 'Style your websites with CSS. Learn layouts, animations, and responsive design techniques.', '🎨'),
('javascript', 'JavaScript', 'Add interactivity to your websites with JavaScript. Learn programming fundamentals and DOM manipulation.', '⚡')
ON CONFLICT (id) DO NOTHING;

-- Insert HTML sessions
INSERT INTO sessions (id, course_id, title, description, content, assignment, tasks, order_index) VALUES
('what-is-html', 'html', 'What is HTML?', 'Introduction to HTML and its role in web development', 'HTML (HyperText Markup Language) is the standard markup language for creating web pages. It describes the structure and content of a webpage using elements and tags.', 'Create your first HTML document with basic structure including DOCTYPE, html, head, and body tags.', ARRAY['Set up a basic HTML5 document structure', 'Add a title to your webpage', 'Include meta tags for character encoding', 'Add a simple heading and paragraph'], 1),
('main-code-html', 'html', 'Main code in HTML', 'Understanding HTML document structure and basic syntax', 'Learn about the essential HTML document structure, including DOCTYPE declaration, html element, head section, and body content. Understand how browsers interpret HTML code.', 'Build a complete HTML page structure with proper nesting and indentation.', ARRAY['Create a well-structured HTML document', 'Add proper indentation and formatting', 'Include comments to explain your code', 'Validate your HTML using online validators'], 2),
('main-tags', 'html', 'Main Tags: h1-h6, p, img, ul/ol', 'Essential HTML tags for content structure', 'Master the most commonly used HTML tags including headings (h1-h6), paragraphs (p), images (img), and lists (ul/ol). Learn proper semantic usage and accessibility considerations.', 'Create a webpage about your favorite hobby using headings, paragraphs, images, and lists.', ARRAY['Use all heading levels appropriately', 'Write descriptive paragraphs', 'Add images with proper alt attributes', 'Create both ordered and unordered lists'], 3),
('page-layout-media', 'html', 'Page Layout + Media (video/audio)', 'Structuring pages and embedding multimedia content', 'Learn how to structure web pages using semantic HTML elements and embed multimedia content like videos and audio files. Understand different media formats and accessibility requirements.', 'Build a multimedia portfolio page with embedded videos and audio.', ARRAY['Structure a page with header, main, and footer', 'Embed a video with controls', 'Add audio content with fallback options', 'Ensure all media has proper accessibility attributes'], 4),
('semantic-elements', 'html', 'Semantic Elements', 'Using HTML5 semantic elements for better structure', 'Discover HTML5 semantic elements like header, nav, main, article, section, aside, and footer. Learn how these elements improve accessibility and SEO.', 'Redesign a previous project using semantic HTML5 elements.', ARRAY['Replace div elements with semantic alternatives', 'Create a proper document outline', 'Use article and section appropriately', 'Add navigation with proper landmarks'], 5),
('forms-inputs-buttons', 'html', 'Forms, Inputs, Buttons', 'Creating interactive forms and user input elements', 'Master HTML forms including various input types, labels, validation attributes, and form submission. Learn about accessibility and user experience best practices.', 'Create a comprehensive contact form with validation.', ARRAY['Build a form with various input types', 'Add proper labels and placeholders', 'Implement client-side validation', 'Style form elements for better UX'], 6)
ON CONFLICT (id, course_id) DO NOTHING;

-- Insert CSS sessions
INSERT INTO sessions (id, course_id, title, description, content, assignment, tasks, order_index) VALUES
('what-is-css', 'css', 'What is CSS & How it Works', 'Introduction to CSS and its relationship with HTML', 'CSS (Cascading Style Sheets) is used to style and layout web pages. Learn how CSS works with HTML, the cascade, inheritance, and specificity.', 'Add basic styling to your HTML project using internal CSS.', ARRAY['Link CSS to HTML using different methods', 'Apply basic styles to text and backgrounds', 'Understand the cascade and specificity', 'Use browser developer tools to inspect styles'], 1),
('box-model', 'css', 'Box Model', 'Understanding the CSS box model concept', 'Master the CSS box model including content, padding, border, and margin. Learn how box-sizing affects element dimensions and layout.', 'Create a visual representation of the box model using CSS.', ARRAY['Demonstrate content, padding, border, and margin', 'Use box-sizing: border-box', 'Create spacing between elements', 'Debug layout issues using developer tools'], 2),
('selectors', 'css', 'Selectors: ID, Class, Element', 'CSS selectors and targeting specific elements', 'Learn different types of CSS selectors including element, class, ID, attribute, and pseudo-selectors. Understand selector specificity and best practices.', 'Style a webpage using various selector types and combinations.', ARRAY['Use element, class, and ID selectors', 'Combine selectors for specific targeting', 'Apply pseudo-classes and pseudo-elements', 'Organize CSS with proper selector hierarchy'], 3),
('units-colors-typography', 'css', 'Units, Colors, Typography', 'CSS units, color systems, and text styling', 'Explore CSS units (px, em, rem, %, vw, vh), color systems (hex, rgb, hsl), and typography properties for creating visually appealing text.', 'Design a typography-focused webpage with various units and colors.', ARRAY['Use different CSS units appropriately', 'Apply various color formats', 'Style text with fonts, sizes, and spacing', 'Create a cohesive color scheme'], 4),
('flexbox-grid', 'css', 'Flexbox, Grid, Media Queries', 'Modern CSS layout techniques and responsive design', 'Master CSS Flexbox and Grid for creating flexible layouts. Learn media queries for responsive design across different screen sizes.', 'Build a responsive layout using both Flexbox and Grid.', ARRAY['Create a flexible navigation with Flexbox', 'Design a card layout using CSS Grid', 'Add media queries for mobile responsiveness', 'Test layout on different screen sizes'], 5),
('forms-styling', 'css', 'Forms Styling', 'Styling form elements and improving user experience', 'Learn to style form elements including inputs, buttons, and form layouts. Understand user experience principles and accessibility in form design.', 'Style the contact form from the HTML course with modern CSS.', ARRAY['Style input fields and buttons', 'Create hover and focus states', 'Design form validation feedback', 'Make forms mobile-friendly'], 6),
('transitions-animations', 'css', 'Transitions, Animations', 'Adding motion and interactivity with CSS', 'Create smooth transitions and keyframe animations. Learn performance considerations and best practices for web animations.', 'Add animations and transitions to enhance user interactions.', ARRAY['Create smooth hover transitions', 'Build keyframe animations', 'Add loading animations', 'Optimize animations for performance'], 7),
('final-project', 'css', 'Final Project', 'Combine all CSS skills in a complete project', 'Apply everything you have learned to create a fully styled, responsive website. Focus on clean code, performance, and user experience.', 'Build a complete responsive website showcasing all CSS techniques.', ARRAY['Plan and design your website layout', 'Implement responsive design patterns', 'Add interactive elements and animations', 'Optimize for performance and accessibility'], 8)
ON CONFLICT (id, course_id) DO NOTHING;

-- Insert JavaScript sessions
INSERT INTO sessions (id, course_id, title, description, content, assignment, tasks, order_index) VALUES
('what-is-javascript', 'javascript', 'What is JavaScript?', 'Introduction to JavaScript and its role in web development', 'JavaScript is a programming language that adds interactivity to websites. Learn how JavaScript differs from HTML and CSS, and its role in modern web development.', 'Write your first JavaScript program and connect it to an HTML page.', ARRAY['Set up JavaScript in an HTML document', 'Use console.log to output messages', 'Understand the browser console', 'Write comments in JavaScript'], 1),
('operators', 'javascript', 'Operators (Arithmetic, Comparison, Logical)', 'JavaScript operators for calculations and comparisons', 'Master JavaScript operators including arithmetic (+, -, *, /), comparison (==, ===, !=, <, >), and logical (&&, ||, !) operators.', 'Create a simple calculator using JavaScript operators.', ARRAY['Perform arithmetic calculations', 'Compare values and understand equality', 'Use logical operators for conditions', 'Build a basic calculator interface'], 2),
('variables-data-types', 'javascript', 'Variables, Data Types', 'Storing and working with different types of data', 'Learn about JavaScript variables (let, const, var) and data types (string, number, boolean, null, undefined, object, array).', 'Create a personal information storage system using different data types.', ARRAY['Declare variables with let and const', 'Work with strings, numbers, and booleans', 'Understand null and undefined', 'Create and manipulate objects and arrays'], 3),
('conditions-loops', 'javascript', 'Conditions, Loops', 'Control flow with if statements and loops', 'Master conditional statements (if, else if, else, switch) and loops (for, while, do-while) to control program flow.', 'Build a number guessing game using conditions and loops.', ARRAY['Write if-else statements', 'Use switch statements appropriately', 'Create for and while loops', 'Build interactive decision-making programs'], 4),
('functions', 'javascript', 'Functions (Declarations, Expressions, Arrow)', 'Creating reusable code with functions', 'Learn different ways to create functions in JavaScript: function declarations, function expressions, and arrow functions. Understand scope and parameters.', 'Create a utility library with various helper functions.', ARRAY['Write function declarations and expressions', 'Use arrow functions appropriately', 'Understand function scope and parameters', 'Create functions that return values'], 5),
('arrays-methods', 'javascript', 'Arrays & Methods', 'Working with arrays and their built-in methods', 'Master JavaScript arrays and their methods including push, pop, shift, unshift, slice, splice, indexOf, and includes.', 'Build a todo list application using array methods.', ARRAY['Create and manipulate arrays', 'Use array methods to add/remove items', 'Search and filter array contents', 'Build a functional todo list'], 6),
('objects', 'javascript', 'Objects', 'Creating and working with JavaScript objects', 'Learn about JavaScript objects, properties, methods, and object-oriented programming concepts. Understand this keyword and object manipulation.', 'Create a student management system using objects.', ARRAY['Create objects with properties and methods', 'Access and modify object properties', 'Understand the this keyword', 'Build a data management system'], 7),
('dom-manipulation', 'javascript', 'DOM Manipulation', 'Interacting with HTML elements using JavaScript', 'Learn to select, modify, and create HTML elements using JavaScript. Master the Document Object Model (DOM) and dynamic content creation.', 'Build an interactive webpage that responds to user actions.', ARRAY['Select elements using various methods', 'Modify element content and attributes', 'Create new elements dynamically', 'Style elements with JavaScript'], 8),
('events', 'javascript', 'Events', 'Handling user interactions and browser events', 'Master JavaScript event handling including click, submit, load, and keyboard events. Learn event listeners and event object properties.', 'Create an interactive form with real-time validation.', ARRAY['Add event listeners to elements', 'Handle different types of events', 'Use the event object effectively', 'Create responsive user interfaces'], 9),
('string-number-methods', 'javascript', 'String & Number methods', 'Built-in methods for manipulating strings and numbers', 'Explore JavaScript string methods (slice, substring, replace, split) and number methods (parseInt, parseFloat, toFixed, Math object).', 'Build a text processing tool with string and number manipulation.', ARRAY['Manipulate strings with built-in methods', 'Format and process numbers', 'Use Math object for calculations', 'Create text analysis tools'], 10),
('advanced-array-methods', 'javascript', 'Advanced Array methods (map, filter, reduce)', 'Functional programming with advanced array methods', 'Master advanced array methods including map, filter, reduce, forEach, find, and some. Learn functional programming concepts.', 'Create a data analysis dashboard using advanced array methods.', ARRAY['Transform data with map method', 'Filter arrays based on conditions', 'Reduce arrays to single values', 'Chain array methods effectively'], 11),
('final-practical-project', 'javascript', 'Final Practical Project', 'Build a complete interactive web application', 'Combine all JavaScript skills to create a fully functional web application. Focus on clean code, user experience, and best practices.', 'Build a complete web application of your choice using all JavaScript concepts.', ARRAY['Plan and design your application', 'Implement all JavaScript features learned', 'Add error handling and validation', 'Test and optimize your application'], 12)
ON CONFLICT (id, course_id) DO NOTHING;

-- Insert project categories
INSERT INTO project_categories (id, title, description, icon) VALUES
('html-css', 'HTML & CSS Projects', 'Build beautiful, responsive websites using HTML and CSS. Perfect for practicing layout and styling skills.', '🎨'),
('fullstack', 'Full-Stack Projects', 'Complete web applications using HTML, CSS, and JavaScript. Build interactive, dynamic websites.', '⚡')
ON CONFLICT (id) DO NOTHING;

-- Insert HTML & CSS projects
INSERT INTO projects (id, category_id, title, description, difficulty, technologies, requirements, instructions, estimated_time) VALUES
('personal-portfolio', 'html-css', 'Personal Portfolio Website', 'Create a professional portfolio website to showcase your skills and projects.', 'Intermediate', ARRAY['HTML5', 'CSS3', 'Flexbox', 'Grid'], ARRAY['Responsive design that works on all devices', 'Navigation menu with smooth scrolling', 'Hero section with your photo and introduction', 'Skills section with progress bars', 'Projects gallery with hover effects', 'Contact form with validation styling', 'Footer with social media links'], 'Start by creating the HTML structure with semantic elements. Use CSS Grid for the main layout and Flexbox for components. Implement a mobile-first responsive design approach. Add smooth animations and transitions for better user experience.', '8-12 hours'),
('restaurant-website', 'html-css', 'Restaurant Landing Page', 'Design an elegant restaurant website with menu, gallery, and reservation section.', 'Beginner', ARRAY['HTML5', 'CSS3', 'CSS Animations'], ARRAY['Header with logo and navigation', 'Hero section with restaurant image', 'About section with restaurant story', 'Menu section with food items and prices', 'Image gallery of dishes', 'Contact information and location', 'Reservation form'], 'Focus on creating an appetizing visual design with warm colors and food imagery. Use CSS animations for menu items and image hover effects. Ensure the design is mobile-friendly.', '6-8 hours'),
('blog-layout', 'html-css', 'Modern Blog Layout', 'Create a clean, modern blog layout with article cards and sidebar.', 'Intermediate', ARRAY['HTML5', 'CSS3', 'CSS Grid', 'Flexbox'], ARRAY['Header with blog title and navigation', 'Main content area with article cards', 'Sidebar with categories and recent posts', 'Article preview with image, title, and excerpt', 'Pagination controls', 'Search functionality styling', 'Footer with links and copyright'], 'Use CSS Grid for the main layout structure. Create reusable card components for articles. Implement a clean typography system and consistent spacing throughout.', '10-14 hours')
ON CONFLICT (id, category_id) DO NOTHING;

-- Insert Full-Stack projects
INSERT INTO projects (id, category_id, title, description, difficulty, technologies, requirements, instructions, estimated_time) VALUES
('todo-app', 'fullstack', 'Advanced Todo Application', 'Build a feature-rich todo app with local storage, categories, and filtering.', 'Intermediate', ARRAY['HTML5', 'CSS3', 'JavaScript', 'Local Storage'], ARRAY['Add, edit, and delete tasks', 'Mark tasks as complete/incomplete', 'Filter tasks by status (all, active, completed)', 'Search functionality', 'Task categories and priority levels', 'Data persistence with localStorage', 'Drag and drop to reorder tasks', 'Export tasks to JSON'], 'Start with the HTML structure for the todo interface. Style with CSS for a modern look. Implement JavaScript functionality for CRUD operations. Use localStorage to persist data between sessions. Add advanced features like drag-and-drop and filtering.', '15-20 hours'),
('weather-app', 'fullstack', 'Weather Dashboard', 'Create a weather application that fetches real-time weather data and displays forecasts.', 'Advanced', ARRAY['HTML5', 'CSS3', 'JavaScript', 'APIs', 'Geolocation'], ARRAY['Current weather display with location', '5-day weather forecast', 'Search for weather by city name', 'Geolocation support for current location', 'Weather icons and animations', 'Temperature unit conversion (C/F)', 'Favorite cities list', 'Responsive design for mobile'], 'Use a weather API (like OpenWeatherMap) to fetch data. Implement geolocation API for current location. Create dynamic UI that updates based on weather data. Add smooth animations and transitions for better UX.', '20-25 hours'),
('expense-tracker', 'fullstack', 'Personal Expense Tracker', 'Build a comprehensive expense tracking application with charts and analytics.', 'Advanced', ARRAY['HTML5', 'CSS3', 'JavaScript', 'Chart.js', 'Local Storage'], ARRAY['Add income and expense transactions', 'Categorize transactions', 'Visual charts for spending analysis', 'Monthly/yearly spending reports', 'Budget setting and tracking', 'Transaction search and filtering', 'Data export functionality', 'Dark/light theme toggle'], 'Design a clean dashboard interface. Implement transaction management with JavaScript. Use Chart.js for data visualization. Create a robust data structure for storing financial data. Add budget alerts and spending insights.', '25-30 hours'),
('quiz-app', 'fullstack', 'Interactive Quiz Application', 'Develop a quiz app with multiple question types, scoring, and progress tracking.', 'Intermediate', ARRAY['HTML5', 'CSS3', 'JavaScript', 'JSON'], ARRAY['Multiple choice questions', 'True/false questions', 'Timer for each question', 'Score calculation and display', 'Progress indicator', 'Question categories', 'High score leaderboard', 'Quiz results summary'], 'Create a question data structure in JSON format. Build a dynamic question display system. Implement timer functionality and score tracking. Add smooth transitions between questions and engaging animations.', '18-22 hours')
ON CONFLICT (id, category_id) DO NOTHING;
